[package]
name = "ruust"
version = "0.1.0"
authors = ["nic <nic@iotato.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
creak = "0.3.0"
hound = "3.4.0"
